//User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const ADD_LISTING = 'ADD_LISTING'
export const DELETE_LISTING = 'DELETE_LISTING'
export const EDIT_LISTING = 'EDIT_LISTING'

export const SET_LISTINGS = "SET_LISTINGS"

export const LOADING = "LOADING"
export const DONE_LOADING = "DONE_LOADING"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const SET_ERRORS = "SET_ERRORS"
export const SET_FAVORITES = "SET_FAVORITES"